real numero1, numero2, numero3, mayor

Inicio

    escriba "Ingrese el primer numero: "
    lea numero1

    escriba "Ingrese el segundo numero: "
    lea numero2

    escriba "Ingrese el tercer numero: "
    lea numero3

    mayor <- numero1

    si numero2 > mayor entonces
        mayor <- numero2
    fin si

    si numero3 > mayor entonces
        mayor <- numero3
    fin si

    escriba "El numero mayor es: ", mayor

Fin